"""add current_amount to Budget model

Revision ID: 235a81dcd4f1
Revises: 31f16d3e657b
Create Date: 2025-07-24 01:26:00.915113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235a81dcd4f1'
down_revision = '31f16d3e657b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('current_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'current_amount')
    # ### end Alembic commands ###