"""Add person_id to Expense model

Revision ID: 31f16d3e657b
Revises: 
Create Date: 2025-07-23 20:51:26.982859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f16d3e657b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'people', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'person_id')
    # ### end Alembic commands ###